name: Epic
description: Group User-Stories under a common issue
title: "[EPIC] <title>"
labels: ["epic"]
body:
  - type: textarea
    id: personas
    attributes:
      label: User roles or personas?
      description: List all personas related user stories will be created for.
      placeholder: "List roles or personas here!"
    validations:
      required: true
  - type: textarea
    id: user-stories
    attributes:
      label: User Stories for Epic
      description: "Break down the epic/process and link a user-story for each step. Create User-Story Issue then use create a task list linking each user story with the # syntax."
      placeholder: "- [ ] #1234"
    validations:
      required: true
  - type: input
    id: time
    attributes:
      label: Time Estimate
      description: What is the initial time estimate for this Epic?
    validations:
      required: false